export const FontStyle = {
  display3Bold: "font-size: 3.2rem; font-weight: 700; font-family: \"SUIT\";",
  display3SemiBold: "font-size: 3.2rem; font-weight: 600; font-family: \"SUIT\";",
  display2Bold: "font-size: 2.8rem; font-weight: 700; font-family: \"SUIT\";", 
  display2SemiBold: "font-size: 2.8rem; font-weight: 600; font-family: \"SUIT\";", 
  display1Bold: "font-size: 2.4rem; font-weight: 700; font-family: \"SUIT\";",
  display1SemiBold: "font-size: 2.4rem; font-weight: 600; font-family: \"SUIT\";",
  headlineBold: "font-size: 2.0rem; font-weight: 700; font-family: \"SUIT\";",
  headlineSemiBold: "font-size: 2.0rem; font-weight: 600; font-family: \"SUIT\";",
  subhead3Bold: "font-size: 1.6rem; font-weight: 700; font-family: \"SUIT\";",
  subhead3SemiBold: "font-size: 1.6rem; font-weight: 600; font-family: \"SUIT\";",
  subhead2Bold: "font-size: 1.4rem; font-weight: 700; font-family: \"SUIT\";",
  subhead2SemiBold: "font-size: 1.4rem; font-weight: 600; font-family: \"SUIT\";",
  subhead1Bold: "font-size: 1.2rem; font-weight: 700; font-family: \"SUIT\";",
  subhead1SemiBold: "font-size: 1.2rem; font-weight: 600; font-family: \"SUIT\";",
  body3Medium: "font-size: 1.8rem; font-weight: 500; font-family: \"SUIT\";",
  body3Regular: "font-size: 1.8rem; font-weight: 400; font-family: \"SUIT\";",
  body2Medium: "font-size: 1.6rem; font-weight: 500; font-family: \"SUIT\";",
  body2Regular: "font-size: 1.6rem; font-weight: 400; font-family: \"SUIT\";",
  body1Medium: "font-size: 1.4rem; font-weight: 500; font-family: \"SUIT\";",
  body1Regular: "font-size: 1.4rem; font-weight: 400; font-family: \"SUIT\";",
  captionMedium: "font-size: 1.2rem; font-weight: 500; font-family: \"SUIT\";",
  captionRegular: "font-size: 1.2rem; font-weight: 400; font-family: \"SUIT\";",
  descriptionMedium: "font-size: 1rem; font-weight: 500; font-family: \"SUIT\";",
  descriptionRegular: "font-size: 1rem; font-weight: 400; font-family: \"SUIT\";",
};